### ISSUE TITLE
Meteoswiss entity not showing

### ISSUE THREAD

**Issue by marcoleder** [websylv/homeassistant-meteoswiss#45]
Dear community

Installation was successful, all sensors (12 in total) are available and pulling data.

I added the following to my configuration file:

```
weather:
  - platform: meteoswiss
    name: MeteoSwiss
    postcode: 8142
    station: WAG
```

However, no entity weather.meteoswiss is available or does show up by default. I also tried omitting the part above in the configuration file, still, nothing seemed to work.

Can anyone give me the solution on how to make the entity visible/available?

Best, Marco
