### ISSUE TITLE
How to get daily max. temperature?

### ISSUE THREAD

**Issue by Schnabulation** [websylv/homeassistant-meteoswiss#64]
Dear all

I would like to create an automation based on the maximum temperature that is expected for today.
I can see that the `weather` entity has that attributes for the following 5 days, but not for today:

```
forecast:
  - datetime: '2022-05-17'
    templow: 13
    temperature: 27
    condition: partlycloudy
  - datetime: '2022-05-18'
    templow: 14
    temperature: 28
    condition: sunny
  - datetime: '2022-05-19'
    templow: 15
    temperature: 29
    condition: partlycloudy
  - datetime: '2022-05-20'
    templow: 17
    temperature: 30
    condition: partlycloudy
  - datetime: '2022-05-21'
    templow: 16
    temperature: 26
    condition: rainy
```

Is it possible to get the value `temperature` and `templow` for today?
